---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: static-sample
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: static-sample
  filterTags:
    # https://fluxcd.io/flux/guides/sortable-image-tags/#using-in-an-imagepolicy-object
    pattern: "[a-f0-9]+-(?P<ts>[0-9]+)" # "^(?P<ts>.*)" # '^sha-(?P<ts>.*)-.+'
    extract: "$ts"
  policy:
    numerical:
      order: asc
