apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s # detect drift and undo kubectl edits
  wait: true # wait for all applied resources to become ready
  prune: true # remove stale resources from cluster
  force: false # enable this to recreate resources on immutable fields changes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  # targetNamespace: apps # set the namespace for all resources
  timeout: 3m0s # give up waiting after three minutes
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
    # namespace: apps
  path: ./apps
