apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 60m0s # detect drift and undo kubectl edits
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./sources
  prune: true
  validation: client
