---
## helm show values jetstack/cert-manager --version v1.12.4
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: v1.12.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 24h
  values:
    installCRDs: true
    prometheus:
      enabled: true
