name: e2e

on:
  workflow_dispatch:
  #push:
  #  branches: [ '*' ]
  #  tags-ignore: [ '*' ]

permissions: write-all ##

jobs:
  kind-e2e:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      
      - name: KinD
        uses: helm/kind-action@v1.5.0
        with:
          config: config/kind.yaml
          cluster_name: kind
          install_only: true
        
      - name: Make
        run: |
          export GITHUB_TOKEN=${{ secrets.PAT }}
          make all

      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git diff
            echo 'run make test and commit changes'
            exit 1
          fi

      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system get Kustomization
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          kubectl -n ${{ env.NS }} get all
          kubectl -n ${{ env.NS }} describe deployment ${{ env.APP }}
          kubectl -n ${{ env.NS }} logs -l app=${{ env.APP }} --all-containers=true
        env:
          APP: static-sample
          NS: static-sample
